name: 'Winch Node'
description: 'Crank the handle'
inputs:
  filename: 
    description: 'Configuration filename'
    required: false
    default: 'winch.yml'
  command:
    description: 'Command'
    required: false
    default: 'ci'
runs:
  using: 'docker'
  image: "docker://winchci/node:latest"
  args:
    - 'winch ${{ inputs.command }} -f ${{ inputs.filename }}'
branding:
  icon: 'anchor'
  color: 'purple'
