name: 'Winch Node'
description: 'Crank the handle'
inputs:
  filename: 
    description: 'Configuration filename'
    required: false
    default: 'winch.yml'
  command:
    description: 'Command'
    required: false
    default: 'ci'
  version:
    description: 'Node version'
    required: false
    default: '--lts'
runs:
  using: 'docker'
  image: "docker://winchci/node:latest"
  args:
    - '. /root/.nvm/nvm.sh; nvm install ${{ inputs.version }}; nvm use ${{ inputs.version }}; winch ${{ inputs.command }} -f ${{ inputs.filename }}'
branding:
  icon: 'anchor'
  color: 'purple'
